# Release container for Argonne EIC software
# Copy over relevant files from builder
#
FROM eicweb.phy.anl.gov:4567/containers/eic_container/eic_builder:latest as builder
RUN cd /opt/spack-environment && spack env activate . && spack gc -y

# Strip all the binaries
RUN find -L /opt/view/* -type f -exec readlink -f '{}' \; | \
    xargs file -i | \
    grep 'charset=binary' | \
    grep 'x-executable\|x-archive\|x-sharedlib' | \
    awk -F: '{print $1}' | xargs strip -s

FROM eicweb.phy.anl.gov:4567/containers/image_recipes/ubuntu_minimal:20.04
LABEL maintainer="Sylvester Joosten <sjoosten@anl.gov>" \
      name="eic_container" \
      group="eic_container" \
      march="native" \
      basedist="ubuntu" \
      base="ubuntu"

## @ENV@ will be automatically expanded to auto-load the 
## runtime environment
ENV DOCKERFILE_DISTRO=ubuntu          \
    DOCKERFILE_DISTRO_VERSION=20.04   \
    DEBIAN_FRONTEND=noninteractive    \
@ENV@

## Copy over files from builder
COPY --from=builder /opt/spack-environment /opt/spack-environment
COPY --from=builder /opt/software /opt/software
COPY --from=builder /opt/view /opt/view
COPY --from=builder /etc/profile.d/z10_spack_environment.sh /etc/profile.d/z10_spack_environment.sh
## Setup fresh bashrc, useful for singularity
COPY bashrc /etc/bash.bashrc
COPY bashrc /root/.bashrc

## Symlink /opt/view to /usr/local
## Maybe in a future release we should install the view directly to /usr/local
## Note that this is mostly useful for downstream use of the container (e.g.
## using the default install prefix for cmake-based builds), as this way
## the users don't have to remember the special /opt/view directory, which is
## more an internal detail of how the container works.
RUN rm -rf /usr/local && ln -s /opt/view /usr/local

## eic-shell and environment scripts. Not strictly needed anymore now we auto-load
## the environment but still provided for backward compatibility (and documentation).
COPY eic-shell /usr/local/bin/eic-shell
COPY --from=builder /etc/profile.d/z10_spack_environment.sh /etc/eic-env.sh

## make sure we have the entrypoints setup correctly
ENTRYPOINT []
CMD ["bash", "--rcfile", "/etc/profile", "-l"]
USER 0
WORKDIR /
SHELL ["/usr/local/bin/eic-shell"]
