# Release container for Argonne EIC software
# Copy over relevant files from builder
#
FROM eicweb.phy.anl.gov:4567/containers/eic_container/eic_builder:@TAG@ as builder
RUN cd /opt/spack-environment && spack env activate . && spack gc -y

# Strip all the binaries
# This reduces the image size from 3.2GB --> 1.7GB so worth the time
RUN find -L /usr/local/* -type f -exec readlink -f '{}' \; | \
    xargs file -i | \
    grep 'charset=binary' | \
    grep 'x-executable\|x-archive\|x-sharedlib' | \
    awk -F: '{print $1}' | xargs strip -s

FROM eicweb.phy.anl.gov:4567/containers/image_recipes/debian_minimal:testing-20210408
LABEL maintainer="Sylvester Joosten <sjoosten@anl.gov>" \
      name="eic" \
      group="eic" \
      march="native" \
      basedist="debian" \
      base="debian"

## @ENV@ will be automatically expanded to auto-load the 
## runtime environment
ENV DOCKERFILE_DISTRO=debian          \
    DOCKERFILE_DISTRO_VERSION=20210408-testing   \
    DEBIAN_FRONTEND=noninteractive    \
@ENV@

## poppler-utils for pdftoppm, is this is right now not supported by the
## Spack version
RUN apt-get -yqq update \
 && apt-get -yqq install --no-install-recommends \
        ghostscript \
        gv \
        poppler-utils \
        parallel \
 && apt-get -yqq autoremove \
 && rm -rf /var/lib/apt/lists/*

## Copy over files from builder
COPY --from=builder /opt/spack-environment /opt/spack-environment
COPY --from=builder /opt/software /opt/software
RUN rm -rf /usr/local
COPY --from=builder /usr/local /usr/local

## eic-shell and environment scripts. Not strictly needed anymore now we auto-load
## the environment but still provided for backward compatibility (and documentation).
COPY eic-shell /usr/local/bin/eic-shell
COPY eic-env.sh /etc/eic-env.sh
COPY eic-env.sh /etc/profile.d/z10_eic-env.s

## also make sure we have the older container_dev command available
COPY eic-shell /usr/local/bin/container_dev

## also make sure we have the older container_dev command available
COPY eic-shell /usr/local/bin/container_dev

## Setup fresh bashrc, useful for singularity
COPY bashrc /etc/bash.bashrc
COPY bashrc /root/.bashrc

## make sure we have the entrypoints setup correctly
ENTRYPOINT []
CMD ["bash", "--rcfile", "/etc/profile", "-l"]
USER 0
WORKDIR /
SHELL ["/usr/local/bin/eic-shell"]
