# Release container for Argonne EIC software
# Copy over relevant files from builder
#
FROM eicweb.phy.anl.gov:4567/containers/eic_container/eic_builder:latest as builder
RUN cd /opt/spack-environment && spack env activate . && spack gc -y

FROM eicweb.phy.anl.gov:4567/containers/image_recipes/ubuntu_minimal:20.04
LABEL maintainer="Sylvester Joosten <sjoosten@anl.gov>" \
      name="eic_container" \
      group="eic_container" \
      march="native" \
      basedist="ubuntu" \
      base="ubuntu"

## @ENV@ will be automatically expanded to auto-load the 
## runtime environment
ENV DOCKERFILE_DISTRO=ubuntu          \
    DOCKERFILE_DISTRO_VERSION=20.04   \
    DEBIAN_FRONTEND=noninteractive    \
@ENV@

## Copy over files from builder
COPY --from=builder /opt/spack-environment /opt/spack-environment
COPY --from=builder /opt/software /opt/software
COPY --from=builder /opt/view /opt/view
COPY --from=builder /etc/profile.d/z10_spack_environment.sh /etc/profile.d/z10_spack_environment.sh
## Setup fresh bashrc, useful for singularity
COPY bashrc /etc/bash.bashrc
COPY bashrc /root/.bashrc
## eic-shell and environment scripts. Not strictly needed anymore now we auto-load
## the environment but still provided for backward compatibility (and documentation).
COPY eic-shell /usr/local/bin/eic-shell
COPY --from=builder /etc/profile.d/z10_spack_environment.sh /etc/eic-env.sh

## make sure we have the entrypoints setup correctly
ENTRYPOINT []
CMD ["bash", "--rcfile", "/etc/profile", "-l"]
USER 0
WORKDIR /
SHELL ["/usr/local/bin/eic-shell"]
