FROM  eicweb.phy.anl.gov:4567/containers/image_recipes/dd4hep_base:latest

LABEL maintainer="Whitney Armstrong <warmstrong@anl.gov>" \
      name="eic_container" \
      group="containers/eic_containers" \
      march="native" \
      basedist="ubuntu" \
      base="dd4hep_base"


ENV PYTHONPATH="/usr/local/lib:${PYTHONPATH}"                            

#RUN source /usr/local/bin/thisroot.sh                                                     \
