name: nightly

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    name: Build and push nightly images
    uses: ./.github/workflows/build-push.yml
    secrets: inherit
    with:
      nightly: true
